SELECT TOP (1000) [Order_ID]
      ,[Product_ID]
      ,[User_ID]
      ,[Order_Date]
      ,[Return_Date]
      ,[Product_Category]
      ,[Product_Price]
      ,[Order_Quantity]
      ,[Return_Reason]
      ,[Return_Status]
      ,[Days_to_Return]
      ,[User_Age]
      ,[User_Gender]
      ,[User_Location]
      ,[Payment_Method]
      ,[Shipping_Method]
      ,[Discount_Applied]
      ,[Revenue]
      ,[Return_Flag]
      ,[Return_Rate_Category]
      ,[Discount_Level]
      ,[Fraud_Score]
      ,[Risk_Category]
      ,[Return_Value]
  FROM [E-commerce_return].[dbo].[ecommerce_returns_synthetic_dat$]
